export const CONSOLE_SET_CHART_OPTIONS = 'CONSOLE_SET_CHART_OPTIONS'
export const CONSOLE_RESET_CHART_OPTIONS = 'CONSOLE_RESET_CHART_OPTIONS'
export const CONSOLE_SET_DATA_LOADING = 'CONSOLE_SET_DATA_LOADING'
