export const SESSION_USER_REQUEST = 'SESSION_USER_REQUEST'
export const SESSION_USER_SUCCESS = 'SESSION_USER_SUCCESS'
export const SESSION_USER_FAILURE = 'SESSION_USER_FAILURE'
export const EDIT_SESSION_USER = 'EDIT_SESSION_USER'
