
export const PEERS_REQUEST = 'PEERS_REQUEST'
export const PEERS_SUCCESS = 'PEERS_SUCCESS'
export const PEERS_FAILURE = 'PEERS_FAILURE'
export const PEER_NAMESPACE_REQUEST = 'PEER_NAMESPACE_REQUEST'
export const PEER_NAMESPACE_SUCCESS = 'PEER_NAMESPACE_SUCCESS'
export const PEER_NAMESPACE_FAILURE = 'PEER_NAMESPACE_FAILURE'
